name: IELTS Monitor

on:
  push:                     # run on every push
  schedule:
    - cron: "*/10 * * * *"   # runs every 10 minutes
  workflow_dispatch:         # allows manual run from Actions tab

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run IELTS monitor
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TO_EMAIL: ${{ secrets.EMAIL_ADDRESS }}
        run: python ietls_monitor.py
